// Generated by `npm run codegen` — do not edit by hand.
//
// Source: Amazon Web Services provider registry.opentofu.org/hashicorp/aws
// Resources: 12
//
// Fields come from the provider schema. The 10 connection slots, display names
// and defaults come from the curated overrides — provider schemas carry no reference
// information, so those cannot be derived.

import type { ResourceSchema } from "@/lib/providers/types";

export const awsGeneratedResources: readonly ResourceSchema[] = [
  {
    type: "aws_vpc",
    displayName: "VPC",
    category: "network",
    description: "Isolated virtual network.",
    fields: [
      {
        key: "cidr_block",
        label: "Cidr Block",
        type: "string",
        required: true,
        defaultValue: "10.0.0.0/16",
        placeholder: "10.0.0.0/16",
      },
      {
        key: "enable_dns_hostnames",
        label: "Enable DNS Hostnames",
        type: "bool",
        required: false,
        defaultValue: true,
      },
      {
        key: "enable_dns_support",
        label: "Enable DNS Support",
        type: "bool",
        required: false,
        defaultValue: true,
      },
      {
        key: "instance_tenancy",
        label: "Instance Tenancy",
        type: "string",
        required: false,
      }
    ],
    slots: [],
  },
  {
    type: "aws_subnet",
    displayName: "Subnet",
    category: "network",
    description: "IP range within a VPC, in one availability zone.",
    fields: [
      {
        key: "cidr_block",
        label: "Cidr Block",
        type: "string",
        required: true,
        defaultValue: "10.0.1.0/24",
        placeholder: "10.0.1.0/24",
      },
      {
        key: "availability_zone",
        label: "Availability Zone",
        type: "string",
        required: false,
        placeholder: "us-east-1a",
      },
      {
        key: "map_public_ip_on_launch",
        label: "Map Public IP On Launch",
        type: "bool",
        required: false,
        defaultValue: false,
      }
    ],
    slots: [
      {
        id: "vpc_id",
        label: "VPC",
        targetType: "aws_vpc",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "aws_internet_gateway",
    displayName: "Internet Gateway",
    category: "network",
    description: "Gives a VPC access to the internet.",
    fields: [],
    slots: [
      {
        id: "vpc_id",
        label: "VPC",
        targetType: "aws_vpc",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "aws_route_table",
    displayName: "Route Table",
    category: "network",
    description: "Routing rules for subnets in a VPC.",
    fields: [],
    slots: [
      {
        id: "vpc_id",
        label: "VPC",
        targetType: "aws_vpc",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "aws_route_table_association",
    displayName: "Route Table Association",
    category: "network",
    description: "Attaches a route table to a subnet.",
    fields: [],
    slots: [
      {
        id: "subnet_id",
        label: "Subnet",
        targetType: "aws_subnet",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      },
      {
        id: "route_table_id",
        label: "Route table",
        targetType: "aws_route_table",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "aws_security_group",
    displayName: "Security Group",
    category: "network",
    description: "Stateful firewall for instances.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: false,
        placeholder: "web-sg",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        defaultValue: "Managed by Terraform",
      }
    ],
    slots: [
      {
        id: "vpc_id",
        label: "VPC",
        targetType: "aws_vpc",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "aws_eip",
    displayName: "Elastic IP",
    category: "network",
    description: "Static public IPv4 address.",
    fields: [
      {
        key: "domain",
        label: "Domain",
        type: "string",
        required: false,
        defaultValue: "vpc",
      }
    ],
    slots: [],
  },
  {
    type: "aws_nat_gateway",
    displayName: "NAT Gateway",
    category: "network",
    description: "Outbound internet access for private subnets.",
    fields: [
      {
        key: "connectivity_type",
        label: "Connectivity Type",
        type: "string",
        required: false,
        defaultValue: "public",
      }
    ],
    slots: [
      {
        id: "subnet_id",
        label: "Subnet",
        targetType: "aws_subnet",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      },
      {
        id: "allocation_id",
        label: "Elastic IP",
        targetType: "aws_eip",
        targetAttribute: "id",
        cardinality: "one",
        required: false,
      }
    ],
  },
  {
    type: "aws_instance",
    displayName: "EC2 Instance",
    category: "compute",
    description: "Virtual machine.",
    fields: [
      {
        key: "ami",
        label: "Ami",
        type: "string",
        required: true,
        placeholder: "ami-0abcdef1234567890",
      },
      {
        key: "instance_type",
        label: "Instance Type",
        type: "string",
        required: true,
        defaultValue: "t3.micro",
      },
      {
        key: "key_name",
        label: "Key Name",
        type: "string",
        required: false,
      },
      {
        key: "availability_zone",
        label: "Availability Zone",
        type: "string",
        required: false,
      },
      {
        key: "monitoring",
        label: "Monitoring",
        type: "bool",
        required: false,
        defaultValue: false,
      }
    ],
    slots: [
      {
        id: "subnet_id",
        label: "Subnet",
        targetType: "aws_subnet",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      },
      {
        id: "vpc_security_group_ids",
        label: "Security groups",
        targetType: "aws_security_group",
        targetAttribute: "id",
        cardinality: "many",
        required: false,
      }
    ],
  },
  {
    type: "aws_ebs_volume",
    displayName: "EBS Volume",
    category: "storage",
    description: "Block storage volume.",
    fields: [
      {
        key: "availability_zone",
        label: "Availability Zone",
        type: "string",
        required: true,
        placeholder: "us-east-1a",
      },
      {
        key: "size",
        label: "Size",
        type: "number",
        required: false,
        defaultValue: 8,
      },
      {
        key: "type",
        label: "Type",
        type: "enum",
        required: false,
        options: ["gp2", "gp3", "io1", "io2", "sc1", "st1"],
        defaultValue: "gp3",
      },
      {
        key: "encrypted",
        label: "Encrypted",
        type: "bool",
        required: false,
        defaultValue: true,
      }
    ],
    slots: [],
  },
  {
    type: "aws_s3_bucket",
    displayName: "S3 Bucket",
    category: "storage",
    description: "Object storage bucket.",
    fields: [
      {
        key: "bucket",
        label: "Bucket",
        type: "string",
        required: true,
        placeholder: "my-app-assets",
        help: "Globally unique.",
      },
      {
        key: "force_destroy",
        label: "Force Destroy",
        type: "bool",
        required: false,
        defaultValue: false,
      }
    ],
    slots: [],
  },
  {
    type: "aws_iam_role",
    displayName: "IAM Role",
    category: "iam",
    description: "Identity that AWS services assume.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: false,
        placeholder: "app-role",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
      },
      {
        key: "assume_role_policy",
        label: "Assume Role Policy",
        type: "string",
        required: true,
        help: "Trust policy document, as JSON.",
      }
    ],
    slots: [],
  },
];

/** Resources in the provider's full catalog, of which the array above is the bundled part. */
export const awsCatalogSize = 1695;
