// Generated by `npm run codegen` — do not edit by hand.
//
// Source: Google Cloud provider registry.opentofu.org/hashicorp/google
// Resources: 15
//
// Fields come from the provider schema. The 9 connection slots, display names
// and defaults come from the curated overrides — provider schemas carry no reference
// information, so those cannot be derived.

import type { ResourceSchema } from "@/lib/providers/types";

export const gcpGeneratedResources: readonly ResourceSchema[] = [
  {
    type: "google_compute_network",
    displayName: "VPC Network",
    category: "network",
    description: "Virtual private cloud network.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "main",
        help: "Name of the resource.",
      },
      {
        key: "auto_create_subnetworks",
        label: "Auto Create Subnetworks",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Leave off when defining subnetworks explicitly on the canvas.",
      },
      {
        key: "routing_mode",
        label: "Routing Mode",
        type: "enum",
        required: false,
        options: ["REGIONAL", "GLOBAL"],
        defaultValue: "REGIONAL",
        help: "The network-wide routing mode to use.",
      },
      {
        key: "mtu",
        label: "Mtu",
        type: "number",
        required: false,
        help: "Between 1300 and 8896. Left unset, GCP uses 1460.",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        help: "An optional description of this resource.",
      }
    ],
    slots: [],
  },
  {
    type: "google_compute_subnetwork",
    displayName: "Subnetwork",
    category: "network",
    description: "IP range carved out of a VPC within one region.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web",
        help: "The name of the resource, provided by the client when initially creating the resource.",
      },
      {
        key: "ip_cidr_range",
        label: "IP Cidr Range",
        type: "string",
        required: true,
        placeholder: "10.0.1.0/24",
        help: "The range of internal addresses that are owned by this subnetwork.",
      },
      {
        key: "region",
        label: "Region",
        type: "string",
        required: true,
        defaultValue: "us-central1",
        help: "The GCP region for this subnetwork.",
      },
      {
        key: "private_ip_google_access",
        label: "Private IP Google Access",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Lets instances without external IPs reach Google APIs.",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        help: "An optional description of this resource.",
      }
    ],
    slots: [
      {
        id: "network",
        label: "Network",
        targetType: "google_compute_network",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "google_compute_firewall",
    displayName: "Firewall Rule",
    category: "network",
    description: "Allows traffic into or out of a VPC.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "allow-ssh",
        help: "Name of the resource.",
      },
      {
        key: "direction",
        label: "Direction",
        type: "enum",
        required: false,
        options: ["INGRESS", "EGRESS"],
        defaultValue: "INGRESS",
        help: "Direction of traffic to which this firewall applies; default is INGRESS.",
      },
      {
        key: "priority",
        label: "Priority",
        type: "number",
        required: false,
        defaultValue: 1000,
        help: "Lower numbers win. Range 0 to 65535.",
      },
      {
        key: "source_ranges",
        label: "Source Ranges",
        type: "stringList",
        required: false,
        placeholder: "0.0.0.0/0",
        help: "If source ranges are specified, the firewall will apply only to traffic that has source IP address in these ranges.",
      },
      {
        key: "target_tags",
        label: "Target Tags",
        type: "stringList",
        required: false,
        help: "A list of instance tags indicating sets of instances located in the network that may make network connections as specified in allowed[].",
      },
      {
        key: "allow",
        label: "Allowed traffic",
        type: "block",
        required: true,
        nesting: "set",
        help: "The list of ALLOW rules specified by this firewall.",
        fields: [
          {
            key: "protocol",
            label: "Protocol",
            type: "enum",
            required: true,
            options: ["tcp", "udp", "icmp", "all"],
            defaultValue: "tcp",
            help: "The IP protocol to which this rule applies.",
          },
          {
            key: "ports",
            label: "Ports",
            type: "stringList",
            required: false,
            placeholder: "22, 80, 443",
            help: "Leave empty for all ports. Not valid when protocol is icmp.",
          }
        ],
      }
    ],
    slots: [
      {
        id: "network",
        label: "Network",
        targetType: "google_compute_network",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "google_compute_router",
    displayName: "Cloud Router",
    category: "network",
    description: "Dynamic routing for a VPC, required by Cloud NAT and VPN.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "main-router",
        help: "Name of the resource.",
      },
      {
        key: "region",
        label: "Region",
        type: "string",
        required: true,
        defaultValue: "us-central1",
        help: "Region where the router resides.",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        help: "An optional description of this resource.",
      }
    ],
    slots: [
      {
        id: "network",
        label: "Network",
        targetType: "google_compute_network",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "google_compute_instance",
    displayName: "VM Instance",
    category: "compute",
    description: "Compute Engine virtual machine.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-1",
        help: "The name of the instance.",
      },
      {
        key: "machine_type",
        label: "Machine Type",
        type: "string",
        required: true,
        defaultValue: "e2-medium",
        help: "The machine type to create.",
      },
      {
        key: "zone",
        label: "Zone",
        type: "string",
        required: true,
        defaultValue: "us-central1-a",
        help: "The zone of the instance.",
      },
      {
        key: "tags",
        label: "Network tags",
        type: "stringList",
        required: false,
        help: "Firewall rules match instances by these tags.",
      },
      {
        key: "boot_disk",
        label: "Boot Disk",
        type: "block",
        required: true,
        nesting: "list",
        maxItems: 1,
        help: "The boot disk for the instance.",
        fields: [
          {
            key: "initialize_params",
            label: "Image",
            type: "block",
            required: true,
            nesting: "list",
            maxItems: 1,
            help: "Parameters with which a disk was created alongside the instance.",
            fields: [
              {
                key: "image",
                label: "Boot image",
                type: "string",
                required: true,
                defaultValue: "debian-cloud/debian-12",
                help: "The image from which this disk was initialised.",
              }
            ],
          }
        ],
      },
      {
        key: "network_interface",
        label: "Network Interface",
        type: "block",
        required: true,
        nesting: "list",
        help: "The networks attached to the instance.",
        fields: [
          {
            key: "access_config",
            label: "External IP",
            type: "block",
            required: false,
            nesting: "list",
            help: "Add one to get an ephemeral public address.",
            fields: [
              {
                key: "nat_ip",
                label: "NAT IP",
                type: "string",
                required: false,
                help: "The IP address that is be 1:1 mapped to the instance's network ip.",
              },
              {
                key: "network_tier",
                label: "Network Tier",
                type: "string",
                required: false,
                help: "The networking tier used for configuring this instance.",
              },
              {
                key: "public_ptr_domain_name",
                label: "Public Ptr Domain Name",
                type: "string",
                required: false,
                help: "The DNS domain name for the public PTR record.",
              }
            ],
          }
        ],
      },
      {
        key: "service_account",
        label: "Service Account",
        type: "block",
        required: false,
        nesting: "list",
        maxItems: 1,
        help: "The service account to attach to the instance.",
        fields: [
          {
            key: "scopes",
            label: "Scopes",
            type: "stringList",
            required: true,
            defaultValue: ["cloud-platform"],
            help: "A list of service scopes.",
          }
        ],
      }
    ],
    slots: [
      {
        id: "subnetwork",
        label: "Subnetwork",
        targetType: "google_compute_subnetwork",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
        path: ["network_interface"],
      },
      {
        id: "email",
        label: "Service account",
        targetType: "google_service_account",
        targetAttribute: "email",
        cardinality: "one",
        required: false,
        path: ["service_account"],
      }
    ],
  },
  {
    type: "google_compute_address",
    displayName: "Static IP Address",
    category: "compute",
    description: "Reserved internal or external IP address.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-ip",
        help: "Name of the resource.",
      },
      {
        key: "address_type",
        label: "Address Type",
        type: "enum",
        required: false,
        options: ["INTERNAL", "EXTERNAL"],
        defaultValue: "EXTERNAL",
        help: "The type of address to reserve.",
      },
      {
        key: "region",
        label: "Region",
        type: "string",
        required: true,
        defaultValue: "us-central1",
        help: "The Region in which the created address should reside.",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        help: "An optional description of this resource.",
      }
    ],
    slots: [],
  },
  {
    type: "google_compute_disk",
    displayName: "Persistent Disk",
    category: "compute",
    description: "Block storage volume attachable to a VM.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "data",
        help: "Name of the resource.",
      },
      {
        key: "zone",
        label: "Zone",
        type: "string",
        required: true,
        defaultValue: "us-central1-a",
        help: "A reference to the zone where the disk resides.",
      },
      {
        key: "type",
        label: "Type",
        type: "enum",
        required: false,
        options: ["pd-standard", "pd-balanced", "pd-ssd", "hyperdisk-balanced"],
        defaultValue: "pd-balanced",
        help: "URL of the disk type resource describing which disk type to use to create the disk.",
      },
      {
        key: "size",
        label: "Size (GB)",
        type: "number",
        required: false,
        defaultValue: 10,
        help: "Size of the persistent disk, specified in GB.",
      }
    ],
    slots: [],
  },
  {
    type: "google_storage_bucket",
    displayName: "Storage Bucket",
    category: "storage",
    description: "Cloud Storage bucket for object data.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "my-app-assets",
        help: "Must be globally unique across GCP.",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "US",
        help: "The Google Cloud Storage location or region.",
      },
      {
        key: "storage_class",
        label: "Storage Class",
        type: "enum",
        required: false,
        options: ["STANDARD", "NEARLINE", "COLDLINE", "ARCHIVE"],
        defaultValue: "STANDARD",
        help: "The Storage Class of the new bucket.",
      },
      {
        key: "uniform_bucket_level_access",
        label: "Uniform Bucket Level Access",
        type: "bool",
        required: false,
        defaultValue: true,
        help: "Disables per-object ACLs in favour of IAM. Recommended.",
      },
      {
        key: "force_destroy",
        label: "Force Destroy",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Allows terraform destroy to delete a bucket that still holds objects.",
      }
    ],
    slots: [],
  },
  {
    type: "google_service_account",
    displayName: "Service Account",
    category: "iam",
    description: "Identity that workloads run as.",
    fields: [
      {
        key: "account_id",
        label: "Account ID",
        type: "string",
        required: true,
        placeholder: "web-runner",
        help: "6 to 30 lowercase letters, digits and hyphens. Becomes the email prefix.",
      },
      {
        key: "display_name",
        label: "Display Name",
        type: "string",
        required: false,
        help: "The display name for the service account.",
      },
      {
        key: "description",
        label: "Description",
        type: "string",
        required: false,
        help: "A text description of the service account.",
      }
    ],
    slots: [],
  },
  {
    type: "google_project_service",
    displayName: "Enabled API",
    category: "project",
    description: "Enables a Google Cloud API on the project.",
    fields: [
      {
        key: "service",
        label: "Service",
        type: "enum",
        required: true,
        options: [
          "compute.googleapis.com",
          "storage.googleapis.com",
          "iam.googleapis.com",
          "run.googleapis.com",
          "sqladmin.googleapis.com",
          "container.googleapis.com"
        ],
        defaultValue: "compute.googleapis.com",
      },
      {
        key: "disable_on_destroy",
        label: "Disable On Destroy",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Leaving this off avoids disabling an API other stacks may depend on.",
      }
    ],
    slots: [],
  },
  {
    type: "google_cloud_run_v2_service",
    displayName: "Cloud Run Service",
    category: "compute",
    description: "Serverless container service.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "api",
        help: "Name of the Service.",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "us-central1",
        help: "The location of the cloud run service",
      },
      {
        key: "ingress",
        label: "Ingress",
        type: "enum",
        required: false,
        options: [
          "INGRESS_TRAFFIC_ALL",
          "INGRESS_TRAFFIC_INTERNAL_ONLY",
          "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
        ],
        help: "Provides the ingress settings for this Service.",
      },
      {
        key: "deletion_protection",
        label: "Deletion Protection",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Whether Terraform will be prevented from destroying the service.",
      },
      {
        key: "template",
        label: "Template",
        type: "block",
        required: true,
        nesting: "list",
        maxItems: 1,
        help: "The template used to create revisions for this Service.",
        fields: [
          {
            key: "containers",
            label: "Containers",
            type: "block",
            required: false,
            nesting: "list",
            help: "Holds the containers that define the unit of execution for this Service.",
            fields: [
              {
                key: "image",
                label: "Image",
                type: "string",
                required: true,
                defaultValue: "us-docker.pkg.dev/cloudrun/container/hello",
                help: "URL of the Container image in Google Container Registry or Google Artifact Registry.",
              },
              {
                key: "env",
                label: "Env",
                type: "block",
                required: false,
                nesting: "set",
                help: "List of environment variables to set in the container.",
                fields: [
                  {
                    key: "name",
                    label: "Name",
                    type: "string",
                    required: true,
                    placeholder: "DB_HOST",
                    help: "Name of the environment variable.",
                  },
                  {
                    key: "value",
                    label: "Value",
                    type: "string",
                    required: false,
                    help: "Literal value of the environment variable.",
                  }
                ],
              }
            ],
          },
          {
            key: "volumes",
            label: "Volumes",
            type: "block",
            required: false,
            nesting: "list",
            help: "A list of Volumes to make available to containers.",
            fields: [
              {
                key: "name",
                label: "Name",
                type: "string",
                required: true,
                help: "Volume's name.",
              },
              {
                key: "cloud_sql_instance",
                label: "Cloud SQL Instance",
                type: "block",
                required: false,
                nesting: "list",
                maxItems: 1,
                help: "For Cloud SQL volumes, contains the specific instances that should be mounted.",
                fields: [
                  {
                    key: "instances",
                    label: "Instances",
                    type: "stringList",
                    required: false,
                    help: "The Cloud SQL instance connection names, as can be found in https://console.cloud.google.com/sql/instances.",
                  }
                ],
              }
            ],
          }
        ],
      }
    ],
    slots: [
      {
        id: "service_account",
        label: "Service account",
        targetType: "google_service_account",
        targetAttribute: "email",
        cardinality: "one",
        required: false,
        path: ["template"],
      },
      {
        id: "cloud_sql_instances",
        label: "Cloud SQL instance",
        targetType: "google_sql_database_instance",
        targetAttribute: "connection_name",
        cardinality: "many",
        required: false,
        attribute: "instances",
        path: ["template", "volumes", "cloud_sql_instance"],
      }
    ],
  },
  {
    type: "google_sql_database_instance",
    displayName: "Cloud SQL Instance",
    category: "storage",
    description: "Managed PostgreSQL, MySQL or SQL Server.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "app-db",
        help: "The name of the instance.",
      },
      {
        key: "database_version",
        label: "Database Version",
        type: "enum",
        required: true,
        options: ["POSTGRES_15", "POSTGRES_14", "MYSQL_8_0", "SQLSERVER_2019_STANDARD"],
        defaultValue: "POSTGRES_15",
        help: "The MySQL, PostgreSQL or SQL Server version to use.",
      },
      {
        key: "region",
        label: "Region",
        type: "string",
        required: true,
        defaultValue: "us-central1",
        help: "The region the instance will sit in.",
      },
      {
        key: "deletion_protection",
        label: "Deletion Protection",
        type: "bool",
        required: false,
        defaultValue: false,
        help: "Used to block Terraform from deleting a SQL Instance.",
      },
      {
        key: "settings",
        label: "Settings",
        type: "block",
        required: false,
        nesting: "list",
        maxItems: 1,
        help: "The settings to use for the database.",
        fields: [
          {
            key: "tier",
            label: "Tier",
            type: "string",
            required: true,
            defaultValue: "db-f1-micro",
            help: "The machine type to use.",
          }
        ],
      }
    ],
    slots: [],
  },
  {
    type: "google_sql_database",
    displayName: "SQL Database",
    category: "storage",
    description: "A database inside a Cloud SQL instance.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "app",
        help: "The name of the database in the Cloud SQL instance.",
      }
    ],
    slots: [
      {
        id: "instance",
        label: "Cloud SQL instance",
        targetType: "google_sql_database_instance",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "google_sql_user",
    displayName: "SQL User",
    category: "iam",
    description: "Database credentials.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "app",
        help: "The name of the user.",
      },
      {
        key: "password",
        label: "Password",
        type: "string",
        required: false,
        help: "Prefer a Secret Manager reference over a literal.",
      }
    ],
    slots: [
      {
        id: "instance",
        label: "Cloud SQL instance",
        targetType: "google_sql_database_instance",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "google_project_iam_member",
    displayName: "IAM Binding",
    category: "iam",
    description: "Grants a role to a principal on the project.",
    fields: [
      {
        key: "project",
        label: "Project",
        type: "string",
        required: true,
        placeholder: "my-project-id",
      },
      {
        key: "role",
        label: "Role",
        type: "enum",
        required: true,
        options: [
          "roles/cloudsql.client",
          "roles/run.invoker",
          "roles/storage.objectViewer",
          "roles/secretmanager.secretAccessor"
        ],
        defaultValue: "roles/cloudsql.client",
      },
      {
        key: "member",
        label: "Member",
        type: "string",
        required: true,
        placeholder: "serviceAccount:app@project.iam.gserviceaccount.com",
      }
    ],
    slots: [],
  },
];

/** Resources in the provider's full catalog, of which the array above is the bundled part. */
export const gcpCatalogSize = 1315;
