// Generated by `npm run codegen` — do not edit by hand.
//
// Source: Microsoft Azure provider registry.opentofu.org/hashicorp/azurerm
// Resources: 9
//
// Fields come from the provider schema. The 11 connection slots, display names
// and defaults come from the curated overrides — provider schemas carry no reference
// information, so those cannot be derived.

import type { ResourceSchema } from "@/lib/providers/types";

export const azureGeneratedResources: readonly ResourceSchema[] = [
  {
    type: "azurerm_resource_group",
    displayName: "Resource Group",
    category: "project",
    description: "Container that everything else belongs to.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "my-app-rg",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      }
    ],
    slots: [],
  },
  {
    type: "azurerm_virtual_network",
    displayName: "Virtual Network",
    category: "network",
    description: "Isolated network within a region.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "my-vnet",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "address_space",
        label: "Address Space",
        type: "stringList",
        required: true,
        defaultValue: ["10.0.0.0/16"],
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_subnet",
    displayName: "Subnet",
    category: "network",
    description: "IP range within a virtual network.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web",
      },
      {
        key: "address_prefixes",
        label: "Address Prefixes",
        type: "stringList",
        required: true,
        defaultValue: ["10.0.1.0/24"],
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      },
      {
        id: "virtual_network_name",
        label: "Virtual network",
        targetType: "azurerm_virtual_network",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_network_security_group",
    displayName: "Network Security Group",
    category: "network",
    description: "Firewall rules for subnets and interfaces.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-nsg",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_public_ip",
    displayName: "Public IP",
    category: "network",
    description: "Public IP address.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-ip",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "allocation_method",
        label: "Allocation Method",
        type: "enum",
        required: true,
        options: ["Static", "Dynamic"],
        defaultValue: "Static",
      },
      {
        key: "sku",
        label: "Sku",
        type: "enum",
        required: false,
        options: ["Basic", "Standard"],
        defaultValue: "Standard",
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_network_interface",
    displayName: "Network Interface",
    category: "network",
    description: "NIC attaching a VM to a subnet.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-nic",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "ip_configuration",
        label: "IP Configuration",
        type: "block",
        required: true,
        nesting: "list",
        fields: [
          {
            key: "name",
            label: "Name",
            type: "string",
            required: true,
            defaultValue: "internal",
          },
          {
            key: "private_ip_address_allocation",
            label: "Private IP Address Allocation",
            type: "enum",
            required: true,
            options: ["Dynamic", "Static"],
            defaultValue: "Dynamic",
          }
        ],
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      },
      {
        id: "subnet_id",
        label: "Subnet",
        targetType: "azurerm_subnet",
        targetAttribute: "id",
        cardinality: "one",
        required: true,
        path: ["ip_configuration"],
      }
    ],
  },
  {
    type: "azurerm_linux_virtual_machine",
    displayName: "Linux VM",
    category: "compute",
    description: "Linux virtual machine.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "web-1",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "size",
        label: "Size",
        type: "string",
        required: true,
        defaultValue: "Standard_B1s",
      },
      {
        key: "admin_username",
        label: "Admin Username",
        type: "string",
        required: true,
        defaultValue: "azureuser",
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      },
      {
        id: "network_interface_ids",
        label: "Network interfaces",
        targetType: "azurerm_network_interface",
        targetAttribute: "id",
        cardinality: "many",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_managed_disk",
    displayName: "Managed Disk",
    category: "storage",
    description: "Block storage disk.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "data-disk",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "storage_account_type",
        label: "Storage Account Type",
        type: "enum",
        required: true,
        options: ["Standard_LRS", "StandardSSD_LRS", "Premium_LRS", "UltraSSD_LRS"],
        defaultValue: "Standard_LRS",
      },
      {
        key: "create_option",
        label: "Create Option",
        type: "string",
        required: true,
        defaultValue: "Empty",
      },
      {
        key: "disk_size_gb",
        label: "Disk Size Gb",
        type: "number",
        required: false,
        defaultValue: 32,
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
  {
    type: "azurerm_storage_account",
    displayName: "Storage Account",
    category: "storage",
    description: "Blob, file and queue storage.",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        placeholder: "myappstorage",
        help: "Globally unique, lowercase.",
      },
      {
        key: "location",
        label: "Location",
        type: "string",
        required: true,
        defaultValue: "westeurope",
      },
      {
        key: "account_tier",
        label: "Account Tier",
        type: "enum",
        required: true,
        options: ["Standard", "Premium"],
        defaultValue: "Standard",
      },
      {
        key: "account_replication_type",
        label: "Account Replication Type",
        type: "enum",
        required: true,
        options: ["LRS", "GRS", "RAGRS", "ZRS"],
        defaultValue: "LRS",
      }
    ],
    slots: [
      {
        id: "resource_group_name",
        label: "Resource group",
        targetType: "azurerm_resource_group",
        targetAttribute: "name",
        cardinality: "one",
        required: true,
      }
    ],
  },
];

/** Resources in the provider's full catalog, of which the array above is the bundled part. */
export const azureCatalogSize = 1073;
